# Setup
title: <font color = 'MediumSpringGreen'> Crispy's Code Singularity </font>
description: <font color='MediumSpringGreen'> Reminisce </font> 
url: https://crispy-down.github.io
baseurl : ""
avatar: /assets/avatar2.png
paginate: 5
permalink: pretty
cover_image: /assets/wall2.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: kwun woo Kwon
  links:
    - https://github.com/Crispy-down
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
disqus: crispycode.disqus.com 



# Specify the author for blog posts
author:
  name: kwun woo Kwon
  url: https://github.com/Crispy-down
  email: brian3092@naver.com
